import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const links = [
  { href: "/", label: "Home" },
  { href: "/docs", label: "Docs" },
  { href: "/todos", label: "Todos" },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav>
            <ul className="flex items-center p-4">
              {links.map(({label,href}, i) => {
                return (
                  <li key={label} className="p-4">
                    <Link href={href}>{label} </Link>
                  </li>
                );
              })}
            </ul>
          </nav>
        </header>
        <main className="flex items-center justify-center" >{children}</main>
       
      </body>
    </html>
  );
}
